---
title: "Tratamento dos dados de *likes* em *skeets*"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    embed-resources: true
execute: 
  cache: true
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)
`%!in%` <- negate(`%in%`)
```
## Dados de likes

Montando lista de likes

```{r}
#| label: carrega-likes

likes <-
  list.files(
    path = "Dados/likes", 
    pattern = "*.rds",
    full.names = TRUE
  ) |> 
  map(
    \(nome) {
      read_rds(nome) |> 
        mutate(
          uri.skeet = 
            nome |> 
            str_remove("\\..*$") |> 
            str_replace("^", "at://did:plc:") |> 
            str_replace("-", "/app.bsky.feed.post/"),
          data.skeet = created_at,
          to.actor =
            nome |> 
            str_remove("\\..*$") |> 
            str_replace("Dados/likes/", "did:plc:") |> 
            str_remove("-.*$"),
          from.actor = 
            actor_data |> 
            map_chr(\(x) x$did),
          from.handle =
            actor_data |> 
            map_chr(\(x) x$handle),
          .keep = "none"
        )
    }
  ) |> 
  list_rbind() 

likes |> write_rds("Dados/likes.rds")
```

Criando listas de actors relacionados com likes

```{r}
#| label: criando-likes-actors

# quem curtiu
liker.actors <- 
  likes |> 
  select(from.actor, from.handle) |> 
  unique()
liker.actors |> write_rds("Dados/liker-actors.rds")

# quem foi curtido
liked.actors <- 
  likes$to.actor |> 
  unique()
liked.actors |> write_rds("Dados/liked-actors.rds")

# quem curtiu ou foi curtido
likes.actors <- 
  c(liker.actors$from.actor, liked.actors) |> 
  unique()
likes.actors |> write_rds("Dados/likes-actors.rds")
```

Ou carregando do disco o já processado: só executa se avaliado manualmente

```{r}
#| label: recarrega-dados-likes
#| eval: false

likes <- read_rds("Dados/likes.rds")
liker.actors <- read_rds("Dados/liker-actors.rds")
liked.actors <- read_rds("Dados/liked-actors.rds")
likes.actors <- read_rds("Dados/likes-actors.rds")
```

Montando a matriz de likes dados

```{r}
#| label: monta-matriz-likes

all.actors <- 
  tibble(
    did = 
      c(likes$from.actor, likes$to.actor) |> 
      unique() |> 
      sort()
  ) |> 
  mutate(num = row_number())
all.actors |> write_rds("Dados/all-actors-likes.rds")

matriz.likes <- 
  likes |> 
  left_join(
    all.actors,
    by = c("from.actor" = "did")
  ) |> 
  rename(from.actor.num = num) |> 
  left_join(
    all.actors,
    by = c("to.actor" = "did")
  ) |> 
  rename(to.actor.num = num) |> 
  select(
    data.skeet, 
    from.actor.num, 
    to.actor.num
  )
matriz.likes |> write_rds("Dados/matriz-likes.rds")
```

## Dados de skeets

Carregando a versão curta

```{r}
#| label: carrega-skeets

skeets <- read_rds("Dados/skeets-curto.rds")
```

Separando os skeets com "cblol" em iniciais e replies/quotes

```{r}
#| label: separando-skeets-iniciais-replies-quotes

skeets.separados <- 
  skeets |> 
  group_by(is.na(uri.reply)) |> # FALSE = reply/quote e TRUE = original
  group_split(.keep = FALSE) |> 
  # set_names(c("reply.quote", "original"))
```

