---
title: "5-grafos-likes"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    embed-resources: true
execute: 
  cache: true
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)
library(tidygraph)
library(ggraph)
library(igraph)
library(viridis)
```

```{r}
#| label: carrega-metricas

all.actors.likes <- read_rds("Dados/all-actors-likes-2.rds")
matriz.likes <- read_rds("Dados/matriz-likes.rds")
vetor.matrizes.dias.likes <- readRDS("Dados/vetor-matrizes-dias-likes.rds")
dia37 <- readRDS(vetor.matrizes.dias.likes[[37]])
metricas_agregadas_dia37 <- read_rds("Dados/metricas_agregadas_dia37.rds")

#metricas_todos_dias <- ("Dados/metricas-todos-dias.rds")
```


```{r}
## 5.2 e 5.3. Construindo o grafo do dia 37

# edges: quem curte (from) → quem recebe like (to)
edges_dia37 <- 
  dia37 |>
  rename(
    from   = actor.influenced.num,
    to     = actor.influencer.num,
    weight = quantos
  ) |>
  mutate(
    from = as.character(from),
    to   = as.character(to)
  )

# nodes: todos os IDs que aparecem em from ou to
nodes_dia37 <- 
  tibble(name = unique(c(edges_dia37$from, edges_dia37$to))) |>
  left_join(
    all.actors.likes |>
      mutate(num = as.character(num)) |>
      select(name = num, handle),
    by = "name"
  )

# construindo o grafo com tidygraph
grafo_dia37 <- 
  tbl_graph(
    nodes = nodes_dia37,
    edges = edges_dia37,
    directed = TRUE
  )

```



```{r}
grafo_dia37 <- 
  grafo_dia37 |>
  activate(nodes) |>
  left_join(
    metricas_agregadas_dia37 |> 
      mutate(actor.num = as.character(actor.num)),
    by = c("name" = "actor.num")
  ) |>
  mutate(
    grau_in    = centrality_degree(mode = "in",  loops = FALSE),
    grau_out   = centrality_degree(mode = "out", loops = FALSE),
    betweenness = centrality_betweenness(),
    eigen       = centrality_eigen()
  )
```

Aí você passa a ter tudo junto:

in_degree / out_degree (baseados em soma de likes)

grau_in / grau_out (baseados em número de conexões diferentes)


```{r}
#as operações abaixo devem agir sobre os nós do grafo
metricas_dia37 <-
grafo_dia37 |>
activate(nodes) |>
as_tibble()

metricas_dia37 |> arrange(desc(grau_in)) |> head(20) |>
write_rds("Dados/metricas_dia37")

```


mantendo quem recebeu 5 curtidas por dia
(nunca uso, mas existe. ggraph(grafo_filtrado, layout = "fr") +)

```{r}

grafo_filtrado <-
grafo_dia37 |>
activate(nodes) |>
filter(grau_in >= 1000)

grafo_filtrado
```


```{r}

set.seed(123)

ggraph::ggraph(grafo_filtrado, layout = "fr") +
geom_edge_link(aes(alpha = weight), show.legend = FALSE) +
geom_node_point(aes(size = grau_in)) +
geom_node_text(aes(label = handle.x),
repel = TRUE,
size = 3) +
scale_size_continuous(name = "Likes recebidos (grau in)",
range = c(2, 10)) +
theme_void() +
ggtitle("Rede de likes – dia selecionado (alguns atores)")

```

```{r}

set.seed(123)

preto <- ggraph(grafo_filtrado, layout = "fr") +
  
  # Arestas suaves e discretas
  geom_edge_link(
    aes(alpha = weight),
    color = "black",
    width = 0.5,
    show.legend = FALSE
  ) +
  
  # Nós com cor proporcional ao grau_in
  geom_node_point(
    aes(size = grau_in, color = grau_in),
    alpha = 0.8
  ) +
  
  # Labels com boa visibilidade
  geom_node_text(
    aes(label = handle.x),
    repel = TRUE,
    size = 3,
    color = "black"  # mais visível sobre fundo escuro
  ) +
  
  # Gradiente bonito, científico e daltonismo-friendly
  scale_color_viridis_c(
    option = "plasma",
    name = "Likes recebidos"
  ) +
  
  # Tamanho proporcional ao grau
  scale_size_continuous(
    range = c(3, 12),
    name = "Grau (in-degree)"
  ) +
  
  # Tema escuro “clean”
  theme_void() +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    legend.position = "right",
    legend.title = element_text(color = "black", size = 10),
    legend.text  = element_text(color = "black", size = 8),
    plot.title   = element_text(color = "black", size = 16, face = "bold")
  ) +
  
  ggtitle("Rede de likes – dia selecionado > 100")

# exportando imagem ----
ggplot2::ggsave(
  filename = "img/rede_do_dia.png",
  plot = preto,
  width = 10,
  height = 7,
  dpi = 300
)

```


```{r}
# selecionar top 30 nós por grau_in

top_nos <- 
  grafo_dia37 |>
  activate(nodes) |>
  filter(rank(-grau_in) <= 30)


set.seed(123)

top_influencers <- ggraph(top_nos, layout = "fr") +
  
  # Arestas mais discretas
  geom_edge_link(
    color = "grey60",
    alpha = 0.8,
    show.legend = FALSE
  ) +
  
  # Nós coloridos pelo grau_out
  geom_node_point(
    aes(size = grau_in, color = grau_in),
    alpha = 0.8
  ) +
  
  # Labels com repel e cor branca
  geom_node_text(
    aes(label = handle.x),
    repel = TRUE,
    size = 3,
    color = "white",
    bg.color = "black",     # fundo do label
    bg.r = 0.15             # borda arredondada
  ) +
  # Escalas bonitas
  scale_color_viridis_c(
    name = "Likes recebidos",
    option = "inferno"
  ) +
  scale_size_continuous(
    name = "Likes recebidos (grau in)",
    range = c(4, 14)
  ) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    legend.position = "right",
    plot.title = element_text(color = "black", size = 16, face = "bold")
  ) +
  ggtitle("Rede de likes – top 30 atores que mais recebem curtida no dia 07/09/2024")

# exportando imagem ----
ggplot2::ggsave(
  filename = "img/top30out.png",
  plot = top_influencers,
  width = 10,
  height = 7,
  dpi = 300
)

```


```{r}
# top 30 por grau_out (quem mais dá like)

top_influenced <-
  grafo_dia37 |>
  activate(nodes) |>
  arrange(desc(grau_out)) |>
  slice(1:30)

set.seed(123)

top_influenced <- ggraph(top_influenced, layout = "fr") +
  
  # Arestas mais discretas
  geom_edge_link(
    color = "grey60",
    alpha = 0.8,
    show.legend = FALSE
  ) +
  
  # Nós coloridos pelo grau_out
  geom_node_point(
    aes(size = grau_out, color = grau_out),
    alpha = 0.8
  ) +
  
  # Labels com repel e cor branca
  geom_node_text(
    aes(label = handle.x),
    repel = TRUE,
    size = 3,
    color = "white",
    bg.color = "black",     # fundo do label
    bg.r = 0.15             # borda arredondada
  ) +
  
  # Escalas bonitas
  scale_color_viridis_c(
    name = "Likes distribuídos",
    option = "inferno"
  ) +
  
  scale_size_continuous(
    name = "Likes distribuídos (grau out)",
    range = c(4, 14)
  ) +
  
  # Tema dark para destacar nós coloridos
  theme_void() +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    legend.position = "right",
    plot.title = element_text(color = "black", size = 16, face = "bold")
  ) +
  
  ggtitle("Rede de likes – top 30 atores que mais curtem no dia 07/09/2024")

# exportando imagem ----
ggplot2::ggsave(
  filename = "img/top30out.png",
  plot = top_influenced,
  width = 10,
  height = 7,
  dpi = 300
)

```

```{r}
library(viridis)

top_influencers <-
  grafo_dia37 |>
  activate(nodes) |>
  arrange(desc(grau_out)) |>
  slice(1:30)

set.seed(123)

top_influencers <- ggraph(top_influencers, layout = "fr") +
  
  # Arestas mais discretas
  geom_edge_link(
    color = "grey60",
    alpha = 0.3,
    show.legend = FALSE
  ) +
  
  # Nós coloridos pelo grau_out
  geom_node_point(
    aes(size = grau_out, color = grau_out),
    alpha = 0.8
  ) +
  
  # Labels com repel e cor branca
  geom_node_text(
    aes(label = handle.x),
    repel = TRUE,
    size = 3,
    color = "white",
    bg.color = "black",     # fundo do label
    bg.r = 0.15             # borda arredondada
  ) +
  
  # Escalas bonitas
  scale_color_viridis_c(
    name = "Likes distribuídos",
    option = "plasma"
  ) +
  
  scale_size_continuous(
    name = " ",
    range = c(4, 14)
  ) +
  
  # Tema dark para destacar nós coloridos
  theme_void() +
  theme(
    plot.background = element_rect(fill = "black", color = NA),
    legend.position = "right",
    plot.title  = element_text(color = "white", size = 16, face = "bold"),
#  legend.text  = element_text(color = "white"),
  legend.title = element_text(color = "white")
  ) +
  
  ggtitle("Rede de likes – top 30 atores que mais curtem")

# exportando imagem ----
ggplot2::ggsave(
  filename = "img/top30curtem.png",
  plot = top_influencers,
  width = 10,
  height = 7,
  dpi = 300
)

```

```{r}
write_rds(metricas_dia37, "Dados/metricas-dia37.rds")
```

