---
title: "Extracao_Thread"
author: "Yasmin Messias Lins"
lang: pt-br
format: html
# format: 
#   pdf:
#     geometry:
#       - top=1in
#       - bottom=1in
#       - left=1in
#       - right=1in
#       - heightrounded
execute: 
  cache: true
---

# SETUP
```{r}
#| label: setup
#| warning: false

#library(bskyr)
library(tidyverse)
#library(readr)
library(jsonlite)
library(atrrr)
#library(ggplot2)
library(igraph)
library(ggraph)
library(tidygraph)
```

# Autenticação

```{r}
#| label: autentica

auth(
  user = 'yasmelinss.bsky.social',
  password = read_lines("senha.txt"),
  overwrite = TRUE
)
```

# Glossário


# Extração

```{r}
#| label: extracao-search-post

querys <- 
  c('cblol','lol')

posts <-
  search_post(
    q = querys,
    limit = 25L,
    since = "2024-08-30",
    until = "2024-09-08"
  ) |>
  select(
    author_handle,
    text,
    uri_comentario = uri,
    reply_count
  ) |>
  filter(reply_count > 0)

view(posts)
```

```{r}
#| label: estracao-get_thread

safe_get_thread <- 
  purrr::possibly(
    get_thread, 
    otherwise = tibble()
    )

cometarios <- 
  posts$uri |> 
  purrr::map_dfr(
    function(post_raiz) {
    url <- convert_at_to_http(post_raiz)
    safe_get_thread(url) |>
      dplyr::mutate(uri_post_raiz = post_raiz)
#      dplyr::mutate(uri_comentario = uri_comentario)
   }
  )
View(thread)

```
