---
title: "Arquivo de extração de dados - teste 5"
author: "Yasmin Messias Lins"
lang: pt-br
format: html
# format: 
#   pdf:
#     geometry:
#       - top=1in
#       - bottom=1in
#       - left=1in
#       - right=1in
#       - heightrounded
execute: 
  cache: true
---

# SETUP
```{r}
#| label: setup
#| warning: false

#library(bskyr)
library(tidyverse)
#library(readr)
library(jsonlite)
library(atrrr)
#library(ggplot2)
library(igraph)
library(ggraph)
library(tidygraph)
```

# Autenticação

```{r}
#| label: autentica

auth(
  user = 'yasmelinss.bsky.social',
  password = read_lines("senha.txt"),
  overwrite = TRUE
)
```

# Glossário


# Extração

```{r}
#| label: extracao-search-post

querys <- 
  c('cblol','lol')

posts <-
  search_post(
    q = querys,
    limit = 50L,
    since = "2024-08-30",
    until = "2024-09-08"
  ) |>
  select(
    handle = author_handle,
    repost_count,
    uri 
  ) |>
  filter(repost_count > 0)

view(posts)
#puxar 15 semanas (5 antes, 5 durante, 5 depois)
#no script (.r) que vai extrair os dados
#write_rds("Dados/...")
#no arquivo qmd que vai processar/analisar os dados
#read_rds()

```

```{r}
#| label: extracao-get-reposts

safe_get_reposts <- 
  purrr::possibly(
    get_reposts, 
    otherwise = tibble()
    )

reposts <- 
  posts$uri |>
  purrr::map_dfr( 
    function(repost) { 
      url <- convert_at_to_http(repost)
      safe_get_reposts(post_url = url) |> 
        dplyr::mutate(uri_post = repost) #está renomeando? 
    } 
  ) 


View(reposts)
```

