---
title: "Terceiro Teste de Raspagem no Bluesky"
author: "Yasmin Messias Lins"
lang: pt-br
format: html
# format: 
#   pdf:
#     geometry:
#       - top=1in
#       - bottom=1in
#       - left=1in
#       - right=1in
#       - heightrounded
execute: 
  cache: false
---

# SETUP
```{r}
#| label: setup
#| warning: false

#library(bskyr)
library(tidyverse)
library(readr)
library(jsonlite)
library(atrrr)
library(ggplot2)
library(igraph)

# funções úteis
quebra <- function(string, tamanho = 80) {
  str_split(string, "\n", simplify = TRUE) |> 
    c() |> 
    sapply(
      \(x)
      sapply(
        1:(nchar(x) %/% tamanho + 1), 
        \(k) str_sub(x, start = (k - 1) * tamanho + 1, end = k * tamanho),
        simplify = TRUE,
        USE.NAMES = FALSE
      ),
      simplify = TRUE,
      USE.NAMES = FALSE
    ) |> 
    unlist() |> 
    paste(collapse = "\n") |> 
    cat()
  
}
formataJSON <- function(string) {
  toJSON(string, pretty = TRUE) |> 
    quebra()
}
```

# Autenticação

```{r}
#| label: autenticando

#autenticação

token <-
  auth(
    user = 'yasmelinss.bsky.social',
    password = read_lines("senha.txt"),
    domain = "https://bsky.app/",
    verbose = TRUE,
    overwrite = FALSE,
    token = NULL
  )
```
