---
title: "2º Arquivo de extração de dados - TESTES"
author: "Yasmin Messias Lins"
lang: pt-br
format: html
# format: 
#   pdf:
#     geometry:
#       - top=1in
#       - bottom=1in
#       - left=1in
#       - right=1in
#       - heightrounded
execute: 
  cache: false
---

# SETUP
```{r}
#| label: setup
#| warning: false

#library(bskyr)
library(tidyverse)
#library(readr)
library(jsonlite)
library(atrrr)
#library(ggplot2)
library(igraph)
library(ggraph)
library(tidygraph)

# funções úteis
quebra <- function(string, tamanho = 80) {
  str_split(string, "\n", simplify = TRUE) |> 
    c() |> 
    sapply(
      \(x)
      sapply(
        1:(nchar(x) %/% tamanho + 1), 
        \(k) str_sub(x, start = (k - 1) * tamanho + 1, end = k * tamanho),
        simplify = TRUE,
        USE.NAMES = FALSE
      ),
      simplify = TRUE,
      USE.NAMES = FALSE
    ) |> 
    unlist() |> 
    paste(collapse = "\n") |> 
    cat()
  
}
formataJSON <- function(string) {
  toJSON(string, pretty = TRUE) |> 
    quebra()
}
```

# Autenticação

```{r}
#| label: autentica

auth(
  user = 'yasmelinss.bsky.social',
  password = read_lines("senha.txt"),
  overwrite = TRUE
)
```


# EXTRAÇÕES DE TESTE

Agora, puxando os posts de usuários já definidos

Preciso puxar 10 posts de cada um


```{r}
#| label: extracao-search-post-TESTE


lista_posts_seguindo <- list()

for (item in seguindo) {
  resultado_3 <-
    search_post(
      q = "a",
      limit = 10L,
      sort = "top",
      since = "2024-08-30",
      until = "2024-09-08",
      author = seguindo
    )
  lista_posts_seguindo[[item]] <- resultado_3
}



posts_seguindo <- dplyr::bind_rows(lista_posts_seguindo)

posts_seguindo |>
  dplyr::glimpse()

posts_seguindo |>
  view()

```





```{r}
#| label: visualizando-em-redes-TESTE1
#| eval: false

#recupera os seguidores e extrai só a coluna actor_handle, virando um vetor de strings.

some_followers_teste <- 
  get_followers(
    actor = "yasminkally.bsky.social", 
    limit = 1
    )$actor_handle

# Para cada seguidor, recupere seu próprio conjunto de seguidores.

followers_of_followers <- 
  some_followers_teste |>
    #executa get_followers() para cada um desses handles.
    purrr::map_dfr( ~ {
      get_followers(
        actor = .x, 
        limit = 200) |>
      #adiciona uma coluna dizendo “de quem são esses seguidores
      mutate(from = .x)
  }) |>
  #from → o usuário original (some_followers)
  #to → o seguidor de cada um deles
  dplyr::rename(to = actor_handle) |>
  dplyr::select(from, to)

```

```{r}
#| label: criando-o-grafo

graph <- 
  #A função graph_from_data_frame() transforma suas relações (from → to) em nós e arestas
  igraph::graph_from_data_frame(
    followers_of_followers,
    #O argumento directed = TRUE indica que a relação tem direção (ex: A → B é diferente de B → A)
    directed = TRUE
    )

# Usando ggraph para vizualizar
#Existem outros layouts: "fr" (Fruchterman-Reingold), "circle", "grid", etc
ggraph::ggraph(graph, layout = "fr") +
  #Desenha as arestas
  ggraph::geom_edge_link() +
  #Desenha os nós
  ggraph::geom_node_point(
    #calcula e mapeia o PageRank de cada nó, nós que são seguidos por perfis influentes ficam maiores
    aes(size = tidygraph::centrality_pagerank())) +
  #Remove eixos, títulos e grades
  ggplot2::theme_void()

```

```{r}
get_followers(actor = "yasmelinss.bsky.social", limit = 200)  |>
  dplyr::glimpse()


```

```{r}
get_follows(actor = "yasmelinss.bsky.social", limit = 200)  |>
  dplyr::glimpse()
```

```{r}

# Retrieve the followers for the main user
some_followers <- get_followers(actor = "yasmelinss.bsky.social", limit = 10)$actor_handle

# For each follower, retrieve their own set of followers.
# This provides a nested view of relationships.
followers_of_followers <- some_followers |>
  purrr::map_dfr(~{
    get_followers(actor = .x, limit = 200) |>
    mutate(from = .x)
  }) |>
  dplyr::rename(to = actor_handle) |>
  dplyr::select(from, to) %>%
  dplyr::add_count(to, name = "n_to") %>%
  dplyr::add_count(from, name = "n_from") %>%
  dplyr::filter(n_to > 1 | n_from > 1) %>%
  dplyr::select(-n_to:-n_from)

```


```{r}

# Construct the network graph and plot
graph <- tidygraph::as_tbl_graph(followers_of_followers, directed = TRUE)

# Use ggraph to visualize the network.
ggraph::ggraph(graph, layout = 'fr') +
  ggraph::geom_edge_link() +
  ggraph::geom_node_point(aes(size = tidygraph::centrality_pagerank()), color = "lightblue") +
  ggraph::geom_node_text(aes(label = name, size = tidygraph::centrality_pagerank(), family = "mono", fontface = "bold"),
                   vjust = 1, hjust = 1, check_overlap = T, color = "white", show.legend = F) +
  ggraph::geom_node_text(aes(label = name, size = tidygraph::centrality_pagerank(), family = "mono"),
                   vjust = 1, hjust = 1, check_overlap = T, color = "blue", show.legend = F) +
  ggplot2::theme_void() +
  ggplot2::theme(legend.position = "bottom")
```

```{r}

my_follows <- get_follows(actor = "yasmelinss.bsky.social",
                              limit = 10)$actor_handle # limit only for demonstration

# For each account you follow, retrieve who they follow.
follows_of_follows <- my_follows |>
  purrr::map_dfr(~{
    get_followers(actor = .x, limit = 100) |>
      mutate(from = .x)
  })

# Now we can check which accounts are popular among the people you already follow
follows_of_follows |>
  dplyr::filter(!actor_handle %in% my_follows) |> # exclude accounts you already follow
  dplyr::count(actor_name, actor_handle, sort = TRUE)
```


```{r}

get_likes("https://bsky.app/profile/yasmelinss.bsky.social/post/3m2iaytbuxk2q")  |>
  dplyr::glimpse()
```

