---
#######################################
### introduzir isto na versão para a banca em diante
# titulo: "Análise de redes sociais: O impacto do bloqueio do X em 2024 na comunidade brasileira de e-sports de League of Legends do Bluesky"
# autores: 
#   nome1: 
#     longo: "Yasmin Messias Lins"
#     curto: "Lins, Y. M."
#   nome2:
#     longo: "Thales de Fante Romão"
#     curto: "Romão, T. F."
# orientador: "Prof. Dr. Marcelo Ventura Freire"
# date: last-modified
# date-format: "YYYY"
# versao: "Original"
# # versao: "Corrigida"
# tituloingles: "Social network analysis: The impact of X's ban in 2024 on Bluesky's Brazilian League of Legends esports community"
# dedicatoria1: |
#   dedicatoria 1 \\
#   dedicatoria 1 \\
#   dedicatoria 1 
# dedicatoria2: |
#   dedicatoria 2 \\
#   dedicatoria 2 \\
#   dedicatoria 2 
# agradecimento1: |
#   agradecimento 1 \\
#   agradecimento 1 \\
#   agradecimento 1 
# agradecimento2: |
#   agradecimento 2 \\
#   agradecimento 2 \\
#   agradecimento 2 
# resumo: |
#   resumo em um único parágrafo compridão entre 500 e 150 palavras
# palavraschave: Palavra chave 1. Palavra chave 2.
# resumoingles: |
#   abstract in a long paragraph with 500 to 1500 words
# palavraschaveingles: Keyword 1. Keyword 2.
#######################################
#
# referências bibliográficas
bibliography: tcc.bib
# escolha entre gerar html ou gerar pdf
format:
  #################################################################
  ### versão para renderizar rápido
  #################################################################
  html:
    lang: pt-BR
    toc: true
    toc-location: left
    # toc-location: right
    toc-title: "Sumário"
    toc-depth: 3
    embed-resources: true
    # minimal: true
  #################################################################
  ### versão impressa, quer como rascunho, quer como versão final
  #################################################################
  # pdf:
  #   ####################
  #   ### opções comuns para todas as versões
  #   #################### 
  #   documentclass: abntex2
  #   # precisa executar `tinytex::tlmgr_install("babel-portuges")`
  #   #   se der erro de que o babel não encontra a opção "brazil"
  #   cite-method: biblatex
  #   biblatexoptions:
  #     - backend=biber
  #     - style=abnt
  #     - justify
  #     - giveninits
  #     - backref=true
  #     - backrefstyle=three
  #     - citecounter=true
  #   toc: true
  #   toc-depth: 4
  #   toc-title: "Sumário"
  #   number-sections: true
  #   # fig-cap-location: bottom
  #   ####################
  #   ### opções para a versão rascunho
  #   #################### 
  #   classoption: 
  #     - article
  #     - a4paper
  #     - openany
  #     - oneside
  #   latex-max-runs: 4
  #   include-in-header: 
  #     text: |
  #       \setlrmarginsandblock{3cm}{3cm}{*}
  #       \setulmarginsandblock{3cm}{3cm}{*}
  #       \checkandfixthelayout
  #       \usepackage{titlesec}
  #       \titleformat{\paragraph}{\normalfont\normalsize\bfseries}{\theparagraph}{1em}{}
  #       \titlespacing*{\paragraph}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
  #       \setcounter{secnumdepth}{4}
  #       \usepackage{indentfirst}
  #   include-before-body:
  #     text: |
  #       \DoubleSpacing
  #   fig-pos: H
  #   ####################
  #   ### opções para a versão para a banca
  #   #################### 
  #   # include-before-body:
  #   #   file: 
  #   #     - capa.tex
  #   #   text: |
  #   #     \DoubleSpacing
  #   # lof: true
  #   # lof-title: "Lista de Figuras"
  #   # lot: true
  #   # lot-title: "Lista de Tabelas"
  #   # include-in-header:
  #   #   text: |
  #   #     \usepackage{titlesec}
  #   #     \titleformat{\paragraph}{\normalfont\normalsize\bfseries}{\theparagraph}{1em}{}
  #   #     \titlespacing*{\paragraph}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
  #   #     \setcounter{secnumdepth}{4}
  #   #     \usepackage{indentfirst}
  #   ####################
  #   ### opções para a versão para o depósito
  #   #################### 
  #   # include-before-body:
  #   #   file: 
  #   #     - capa.tex
  #   # lof: true
  #   # lof-title: "Lista de Figuras"
  #   # lot: true
  #   # lot-title: "Lista de Tabelas"
  #   # include-in-header:
  #   #   text: |
  #   #     \usepackage{titlesec}
  #   #     \titleformat{\paragraph}{\normalfont\normalsize\bfseries}{\theparagraph}{1em}{}
  #   #     \titlespacing*{\paragraph}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
  #   #     \setcounter{secnumdepth}{4}
  #   #     \usepackage{indentfirst}
---

\textual

# Introdução

## Revisão Bibliográfica



### Suspensão de Plataformas no Brasil

No século XI, o capitalismo está centrado na extração e uso de um tipo de material em particular: dados, cuja recordação se torna cada vez mais acessível por tecnologias que digitalizam atividades e dão lugar para novas indústrias centradas em plataformas digitais [@Srnicek2017]. Segundo @Dijck2019, plataformas digitais são arquiteturas programáticas desenhadas para organizar interações entre usuários, alimentadas por dados, automatizadas e organizadas por algoritmos e interfaces, formalizadas através de relações de posse impulsionadas por modelos de negócios e regidas por termos de uso. Sobre o papel das plataformas digitais nos mercados emergentes de extração de dados, é possível observar que:

> Ao fornecer um espaço digital para que outras pessoas interajam, as plataformas se posicionam de forma a extrair dados de processos naturais (condições climáticas, ciclos de cultivo etc.), de processos de produção (linhas de montagem, fabricação em fluxo contínuo etc.) e de outras empresas e usuários (rastreamento na web, dados de uso etc.). Elas são um aparato extrativo de dados (@Srnicek2017, p. 32, tradução nossa).

A adoção em larga escala de plataformas é capaz de moldar as interações e causar disrupções societais, ao mesmo tempo que estas são moldadas pelo ecossistema em que ganham forma [@Dijck2019]. O potencial de influência dessas é evidente em acontecimentos como a adoção de dados de usuários do Facebook pela Cambridge Analytica para influenciar a eleição de 2016 dos Estados Unidos, bem como a disseminação de notícias falsas que o Projeto de Lei 2630/2020, conhecido por "PL das *Fake News*", busca combater [@Pereira2024]. 

Em resposta à crescente influência das plataformas, os Estados Nacionais buscam tomar medidas proteger sua soberania nacional da influência dessas *Big Techs* globais [@Pereira2024], com as legislações europeia e francesa buscando definir uma categoria específica para as plataformas digitais desde 2015 [@Seto2021]. @Urupa2020 destacam como sendo motivadores a regulação de plataformas digitais três fatores principais: o crescimento do poder desses agentes, os problemas envolvendo a relação assímetrica com usuários e a insuficiência dos instrumentos normativos para lidar com problemas, garantir competição e assegurar direitos e deveres legais. Nesse contexto, um dos principais desafios para a regulação é o fato de estados competirem entre si por controle sobre o meio digital com seus poderes assimétricos, de forma que, embora tenham a capacidade de determinar a natureza e velocidade da mudança, as organizações globais mantém o poder de controlar a direção da mudança através das plataformas digitais [@Floridi2019].  Em função disso, as Nações Unidas lançaram em 2019 o “Painel de Alto Nível para a Cooperação Digital”, que inclui recomendações como o asseguramento de bens públicos, o combate contra às violações de direitos humanos e o estabelecimento de um sistema de governança que inclua também usuários e não seja formado apenas por agentes privados (como as plataformas) [@Urupa2020].

No contexto brasileiro, a Lei do Marco Civil da *Internet*, que entrou em vigor em 2014, surge da necessidade de definir os fundamentos de disciplina do uso da internet após uma intensa revolução digital, fundamentando-se em três pilares: neutralidade da rede, privacidade de usuários e liberdade de expressão do pensamento [@Leite2016]. Ainda assim, @Barbosa2023 descreve a regulação de casos envolvendo plataformas digitais no Brasil como mais conservadora em comparação às medidas regulatórias digitais tomadas pela União Europeia, cujas normas buscam extensivamente proibir práticas abusivas e proteger a competitividade. Similarmente, @Seto2021 destaca através da revisão de literatura a possibilidade pouco discutida de o Estado oferecer alternativas públicas ao serviço de plataformas privadas e incentivar iniciativas cidadãs, em vez de somente buscar regular a atuação das existentes.

No Brasil, casos de regulação de plataformas digitais são esparsos, porém de grandes proporções: em janeiro de 2007, a Justiça de São Paulo bloqueou o acesso ao Youtube por 48 horas após um processo movido por Renato Malzoni, que pedia a remoção permanente de um vídeo com cenas íntimas entre ele e a apresentadora de TV Daniela Cicarelli, filmados em uma praia da Espanha por um *paparazzi* e postado na plataforma sem autorização do casal [@Folha2007]. Similarmente, em outubro de 2013, um juíz de São Paulo intimou à bloquear o acesso ao Facebook em todo o país se a plataforma não removesse publicações consideradas ofensivas da modelo e apresentadora de TV Luize Altenhofen, porém o Facebook cumpriu a ordem e o bloqueio não ocorreu [@Estadao2013]. [Em dezembro de 2015, o aplicativo de mensagens WhatsApp foi suspenso por 12 horas após decisão jucidiária da juíza Sandra Regina Nostre Marques, da 1ª Vara Criminal de São Bernardo do Campo, em razão da plataforma não ter atendido à uma ordem judicial que solicitava dados referentes à uma investigação do Primeiro Comando da Capital (PCC)]{.mark} [@Estadao2015]. [Analogamente, o Telegram foi bloqueado nacionalmente por 48 horas em março de 2022 por descumprir determinações judiciais, cujas exigências incluíam a nomeação de um representante legal no Brasil, a apresentação de um plano de combate à desinformação e a remoção de links do canal oficial de Jair Messias Bolsonaro que davam acesso a documentos de um inquérito sigiloso. O cumprimento dessas ordens pelo fundador do aplicativo, Pavel Durov, levou ao fim imediato da suspensão]{.mark} [@G12022]. Nestes casos, o Marco Civil da *Internet* que a defende como sendo "essencial ao exercício da cidadania" [@Brasil2014] é colocado em questão pelo poder do Estado de realizar o desligamento repentino de aplicativos ou plataformas digitais, poder esse que pode ser visto como equivalente ao que @Wu2010 descreve como "*master switch*" ou chave mestra da comunicação, um alerta sobre o perigo da existência de tamanho poder para as democracias. 

O caso mais recente de suspensão de plataformas digitais foi o bloqueio da rede social X (antigo Twitter), em função do descumprimento de ordens judiciais pela nomeação de um representante legal no Brasil [@G12024]. O bloqueio durou cerca de 5 semanas, uma das suspensões mais longas de plataformas digitais no país. Esse acontecimento, suas consequências e relevância serão abordados com maior aprofundamento no decorrer da redação.



### Marketing de Redes Sociais

De acordo com @Kaplan2010, redes sociais são um grupo de aplicativos hospedados na Internet, que se baseiam nos fundamentos ideológicos e tecnológicos da Web 2.0 e que permitem a criação e o intercâmbio de conteúdo gerado pelos usuários. Dessa forma, as redes sociais virtuais se destacam como um mecanismo de comunicação que permite um maior alcance de informações e interações do que aqueles possíveis em canais anteriores à era digital, mudando a forma com a qual pessoas interagem entre si e com marcas. Em particular, a natureza interativa desses canais transformou os consumidores de observadores passivos de conteúdo em participantes ativos que agora criam grandes quantidades de conteúdo por meio de suas conversas, interações e comportamentos on-line [@Malthouse2013].

O termo rede social é abrangente em definição, reunindo ambientes virtuais com funcionalidades muito diferentes entre si. Em vista disso, os autores @Kaplan2010 definem seis tipos de redes sociais de acordo com a forma em que os processos sociais ocorrem nestas: projetos colaborativos (como Wikipedia), blogs e microblogues (como X, antigo Twitter), comunidades de conteúdo (como YouTube e Twitch), sites de networking social (como Facebook e LinkedIn), mundos de jogos virtuais e mundos sociais virtuais (como Second Life). Redes sociais que surgiram depois de 2010, como TikTok e Instagram, ainda podem ser categorizadas dentre os seis tipos estabelecidos pelos autores como comunidade de conteúdo e site de networking social, respectivamente, de acordo com suas estruturações. Dessas, as mais comumente referidas pelo termo "redes sociais" são os sites de networking social e as plataformes de microblogs, com redes sociais como X e BlueSky unindo características de ambas categorias em suas funcionalidades.
  
O acesso rápido e amplo aos consumidores-alvo, até mesmo em nível internacional, é uma vantagem das redes sociais para esforços de marketing [@Ravi2021], com campanhas promocionais digitais estando entre as estratégias mais comuns para agências e organizações de publicidade ou comunicação. Essas estratégias, conhecidas como *Social Media Marketing* (SMM), têm como principal atrativo o retorno rápido ao mesmo tempo que permitem informar consumidores da marca, construir posicionamento e adquirir *feedback* a custos mais baixos que através de canais físicos.
  
Com a instalação das redes sociais no cotidiano dos consumidores, @Tuten2015 alegam que um novo “P” pode ser adicionado ao mix de marketing, resultando nos 5 “P”s de praça, produto, promoção, preço e participação em marketing de redes sociais:
  
>Os canais de redes sociais oferecem aos consumidores um acesso sem precedentes. Os consumidores discutem, contribuem, colaboram e compartilham — com as marcas e entre si. A cultura do marketing mudou para uma cultura informal, focada na crença de que os clientes estão no controle. O guru do marketing Peter Drucker disse uma vez a famosa frase: “O objetivo de uma empresa é criar um cliente”. Com o alcance e a influência da comunidade nas mídias sociais, podemos expandir essa definição: o objetivo de uma empresa é criar clientes que criem outros clientes. Essa participação no processo é o novo quinto P do marketing (op.cit., p. 21, tradução nossa).



#### Influenciadores digitais ou *Social Media Influencers*

Em explorar como as relações sociais são construídas em ambientes virtuais, @Baym2010 descrevem como um espaço (plataforma) e práticas (linguagem, hábitos, nacionalidade ou interesses) em comum contribuem para a formação de comunidades em redes sociais, que desenvolvem normas próprias e as perpetuam através da interação entre membros. Sites de networking social como o Facebook tendem a incentivar o surgimento de comunidades na incorporação de ferramentas para auto-apresentação, que fornecem categorias com as quais criar identidades, incluindo dados demográficos como idade, local de residência e interesses gerais. Tais ferramentas também podem ter o resultado não-intencional de facilitar na construção de identidades falsas ou alteradas, levando a um entendimento geral construído ao longo do tempo da distinção entre personalidades *on-line* e *off-line* [@Baym2010].

A honestidade percebida na forma em que uma personalidade virtual se porta em relação a sua comunidade é crucial para sua reputação e influência, fazendo com que outros usuários a vejam como semelhantes a eles e considerem mais valiosas suas opiniões ou recomendações [@Forbes2016]. Esse princípio, sustentado pela teoria de aprendizagem social, é o que dá origem aos influenciadores de redes sociais (social media influencer - SMI), representando um novo tipo de endossantes independentes que moldam as atitudes do público por meio de blogs, postagens e do uso de outras mídias sociais [@Freberg2011]. Atuando como pseudo-celebridades altamente segmentadas, estes influenciadores digitais representam para o marketing de influência uma ferramenta de relações públicas bem-sucedida que permite que as marcas e os consumidores se conectem em um nível mais pessoal [@Glucksman2017]. 

Os relacionamentos parassociais, inicialmente conceituados por Horton e Wohl (1956), descrevem vínculos unilaterais com figuras da mídia. Na atualidade e através das redes sociais, esses relacionamentos são cada vez mais comuns, com o número de seguidores e a autoridade percebida dessas personalidades ampliando o impacto das mensagens emocionais propagadas por estes [@Giles2002]. [Outros aspectos, como conhecimento e experiência, auto-confiança, articulação na fala e grau de identificação com o consumidor-alvo demonstrados são características importantes de um influenciador, que afetam a confiabilidade de seu *word-of-mouth* (marketing boca-a-boca) eletrônico [@Forbes2016]. Sendo assim, a multitude de atributos de um influenciador digital, moldados ou não a partir de sua identidade verdadeira, afetam a eficácia do marketing de influência proporcionalmente à sua compatibilidade com a imagem que a marca deseja propagar, juntamente de características gerais que estão diretamente relacionadas à capacidade de influenciar.



### Indústria de *Games* enquanto Indústria Criativa

Jogos eletrônicos ou *games*, além de servirem como passa-tempo e atividade de lazer, representam um ambiente de dados empíricos valiosos para a criação de conhecimento, exercendo papel central na mídia, redes e cenário sociotécnico da atualidade [@Taylor2019]. Segundo dados do 12º Relatório PGB [@PGB2025], desenvolvido pela Go Gamers e SX Group em parceria com a ESPM e Blend New Research e aplicada nos países Argentina, Chile, Colômbia, México, Peru e Brasil, 82,8% dos participantes relataram ter o costume de jogar algum tipo de jogo digital, um crescimento de 8,9% em relação à edição anterior (73,9%), de 2024.

@Terranova2000 incentiva o debate sobre como trabalhos culturais e técnicos da internet são uma característica predominante da economia pós-industrial, em que indivíduos contribuem com esforços laborais para plataformas comercializadas desde a produção de vídeos no YouTube à criação de postagens em páginas pessoais de redes de networking social. No contexto de jogos eletrônicos, essas plataformas ofereceram algumas das primeiras oportunidades e normas para a monetização do ato de jogar, bem como de atividades criativas na criação de conteúdo através de jogos eletrônicos, amplamente descrito por *user generated content* (UGC) [@Taylor2019].

A transmissão de jogos eletrônicos como uma atividade monetizada surge de uma multitude de fatores. Para aquele que realiza as transmissões, o *streamer*, os principais motivadores são as conexões sociais (como o desejo de compartilhar o ato de jogar com amigos), a amplificação da experiência de jogo através da introdução de telespectadores, as performances criativas e capacidade de auto-expressão através da interação com uma audiência expressiva e as aspirações profissionais de sustentar-se através de um *hobby* ou contribuir para o crescimento indústria de *games* através da publicidade [@Taylor2019]. Em especial, o aspecto relacional das transmissões ao vivo é explicado por @Taylor2019 como um componente importante para o aspecto financeiro da atividade, onde doações e inscrições são apresentadas como formas de expressar gratidão ao criador de conteúdo e tendem a serem seguidas por agradecimentos diretos deste. Desta forma, *streamers* atuam de forma semelhante à influenciadores digitais e possuem um incentivo financeiro direto para promover a parassociabilidade de sua audiência, cuja generosidade é a principal fonte de remuneração.



### Indústria de *E-Sports*

Existe um extenso debate sobre a diferenciação ou a semelhança dos esportes eletrônicos com os esportes tradicionais [@Wollesen2025; @Block2021]. O presente trabalho não busca expandir a discussão da classificação ou não dos esportes eletrônicos como esportes. Pelo contrário, ele já carrega essa premissa e busca expandir os horizontes da aplicação do cenário a partir disso. Utiliza-se então da definição dos autores @Juho2017, em que *e-sports* referem-se a partidas competitivas (amadoras ou profissionais) de vídeo games que podem ser coordenadas por instituições que realizam torneios, onde os *players* (jogadores) ou *pro-players* (jogadores profissionais) costumeiramente pertencem a times que podem ser patrocinados por outras instituições, gerando assim, um negócio.

:::callout
Transmissões online (*streaming*) e eventos híbridos (campeonatos com torcida que são também transmitidos de forma online) são as principais formas de disseminação dos *e-sports*, nos quais toda a atividade esportiva (antes, durante e após o evento) é mediada por computadores, facilitando a obtenção de dados dos telespectadores [@Juho2017]. Nesse contexto, @Cheung2011 definem o espectador de jogos eletrônicos como uma pessoa cujas intenções variam entre assistir ao jogo casualmente e ser um fã em torneios competitivos de jogos, fazendo parte de um "ecossistema de espectadores" onde normas sociais são estabelecidas e experiências emocionais são compartilhadas. Os autores também destacam os "círculos de observação" como sendo representativos das constribuições performáticas dos emissores e da platéia que acontecem ao redor do jogo, cuja narração e comentários contribuem esforços laborais para a criação de uma experiência agradável para o espectador [@Cheung2011].
:::

Em sua *Motivation Scale for Sport Consumption* (Escala de Motivação de Consumo de Esportes), @Trail2001 identificam conquistas (sentir-se realizado com o sucesso do time), escapismo (uma fuga da vida comum), interação social, aquisição de conhecimento, habilidades físicas dos jogadores e atração física como os construtos motivacionais mais positivamente correlacionados ao consumo de mídias esportivas tradicionais e aos fãs de esportes tradicionais. Aplicada ao consumo de *e-sports*, muitos dos motivos permanecem os mesmos [@Cheung2011], porém a aquisição de conhecimento se destaca como o construto motivacional mais associado à intenção de assistir *e-sports* [@Macey2025].

No ambiente virtual das redes sociais, os torneios de *e-sports* são promovidos em grande parte por *mídias propagáveis* como memes, análises, clipes e reações [@Taylor2019]. De acordo com @Jenkins2015, propagabilidade se refere ao potencial cultural e técnico de públicos compartilharem conteúdos por motivos próprios, com ou sem a permissão dos detentores de direitos autorais. Aspectos que influenciam a propagabilidade de mídias incluem o fácil acesso, portabilidade, reutilizabilidade, relevância para públicos amplos e participação em um fluxo constante de material [@Jenkins2015]. A troca social inerente aos esportes, ampliada pelo fácil acesso à transmissão, reprodução e veiculação dos *e-sports* fazem deles mídias altamente propagáveis, em que fãs não são apenas consumidores ou telespectadores mas produtores ativos de conteúdo.



#### League of Legends

Atualmente, League of Legends (LoL) se destaca como um dos jogos eletrônicos e *e-sports* mais relevantes do mercado, ocupando consistentemente a primeira ou segunda posição em jogos mais assistidos na plataforma Twitch no ano de 2025 [@TwitchMetrics]. O título, do gênero *Multiplayer Online Battle Arena* (MOBA, Arena de Batalha Multijogador Online), é um jogo *on-line* desenvolvido pela empresa Riot Games em 2009, com as partidas nos modos de jogo principais sendo compostas por duas equipes de 5 jogadores, nas quais cada jogador toma controle de um personagem e são esperados a trabalharem em conjunto para destruir a base inimiga. [@Cauteruccio2023]

Devido a complexidade das partidas e o nível de habilidade demandado, um grande cenário competitivo vem crescendo ao redor do jogo ao passar dos anos. De acordo com @Cauteruccio2023, o principal evento de *e-sports* de League of Legends é o LoL World Championship (também conhecido como *Worlds*), onde as melhores equipes do mundo participam e disputam os campeonatos competindo por prêmios multimilionários em formato de torneio. As transmissões ao vivo das ligas geralmente são transmitidas por diferentes serviços *streamings* como Twitch e Youtube e o número de visualizações são expressivos, com mais de 99 milhões contabilizadas mundialmente durante a final do Worlds de 2018 [@Cauteruccio2023].

::: callout
Em 2025, o cenário competitivo de League of Legends foi formado por cinco ligas regionais: Coréia do Sul (LCK), Américas (LTA), Europa, Oriente Médio e África (LEC), China (LPL) e Ásia-Pacífico (LCP), nas quais times de uma mesma região competem entre si por vagas nas competições internacionais [@LoL2025]. Anunciada em Junho de 2024 e fundada em 31 de outubro de 2024, a liga de LoL das Américas (LTA) uniu as principais ligas americanas América do Norte (LCS), Campeonato Brasileiro de League of Legends (CBLOL) e Liga Latinoamérica (LLA) em um único ecossistema com duas conferências: LTA Norte (baseada na LCS) e LTA Sul (baseada no CBLOL) [@Riot2024LTA]. No entanto, o fim da união LTA foi anunciado em menos de um ano após sua fundação, em 29 de Setembro de 2025, com a declaração do retorno do CBLOL e LCS como ligas independentes em 2026, assegurando uma vaga no *Worlds* para o time brasileiro vencedor da liga regional [@CBLOL2025].
:::




### Ciência de Dados

Com o avanço da internet, a coleta e a circulação de informações passaram a ocorrer em volumes e velocidades cada vez maiores. O valor destes dados são reconhecidos globalmente, com muitas organizações adotando estratégias orientadas por dados de forma a fazer decisões melhor informadas [@Wedel2016]. 

A necessidade de estudar dados como uma ciência à parte e não apenas através de suas aplicações em pesquisa e indústria leva ao surgimento da Ciência de Dados, que recebeu diversas definições ao longo dos anos. @Zhu2015 consolidam as várias conceituações ao definir Ciência de Dados como a teoria, o método e a tecnologia de estudar a natureza dos dados, tendo dois componentes principais. O primeiro componente é o estudo dos padrões e regras dos próprios dados, explorando a natureza dos dados sem necessariamente levar em consideração seu significado no mundo real. O segundo componente é o estudo das leis do mundo natural refletidas nos dados, de forma a inferir informações sobre a realidade através do estudo de dados.

A Ciência de Dados é por natureza um campo interdisciplinar, tendo aplicações comuns em diversas ciências pela forma que transforma dados desordenados em informações úteis que apoiam ou guiam decisões. De acordo com @Ozsu2024, o sucesso da ciência de dados é evidente em campos como as ciências da saúde, onde a análise de teias sociais permite o rastreamento de epidemias; em sistemas financeiros, em que a análise de grandes volumes de dados podem guiar investimentos e até mesmo para a indústria de atendimento ao consumidor, na qual o avanço de *chatterbots* auxilia no atendimento.


De acordo com @Tabani2020, embora a análise de marketing seja um tópico altamente relevante na atualidade, o potencial dela em negócios reais ainda não é totalmente realizado em razão do crescente volume e complexidade de dados disponíveis através das redes sociais, ferramentas digitais e aplicações de software. O artigo aponta que barreiras na adoção desta abordagem incluem a falta de estratégias abrangentes, expertise, recursos e dados de qualidade, dentre outros fatores. @Hauser2007 descreve que para alcançar entendimentos práticos e aplicáveis para o marketing, é o papel do analista de dados minerar, analisar, interpretar e apresentar a informação de forma a convertê-lá em inteligência acionável, de forma a acompanhar, segmentar e modelar o 'DNA informático' do consumidor. Neste contexto, é evidente que as informações em si não são tão úteis para organizações quanto a inteligência de mercado necessária para analisá-las. 

A análise de redes sociais têm emergido como uma ferramenta crítica para o entendimento do comportamento do consumidor na era digital, sendo capaz de providenciar discernimentos superiores aos de modelos tradicionais de segmentação demográfica e psicográfica [@Dam2022]. De forma abrangente, este método pode ser definido como toda forma de análise de dados estruturados (organizados em estrutura pré-definida) e não-estruturados (sem formato predeterminado) provenientes de redes sociais (*microblogues*, *sites de networking social* ou *comunidades de conteúdo*), independente do formato destas [@Gandomi2015]. Embora aplicações em marketing sejam a principal utilização da análise de redes sociais em tempos recentes, a diversidade de dados presentes nas redes sociais permite o uso em pesquisas em diversas disciplinas como psicologia, sociologia, antropologia e outras. 

Os autores @Gandomi2015 classificam as fontes de informações em redes sociais entre conteúdos gerados por usuários (sentimentos, imagens, vídeos e marcações) e interações entre usuários da rede (pessoas, organizações e produtos). Através desta divisão, os autores segmentam a análise de redes sociais em dois grupos: a análise baseada *em conteúdo* e a análise baseada *em estrutura*. A análise *baseada em conteúdo* tem como objeto de estudo os dados publicados por usuários, comumente desestruturados e ruidosos, através de métodos de análise de texto, aúdio e vídeo como a análise de sentimento. Em contraste, a análise *baseada em estrutura*, busca analisar os atributos estruturais de uma rede social e extrair inteligência das relações entre as entidades participantes, como através de grafos sociais explicando conexões entre usuários.

Para a obtenção dos dados de redes sociais, a mineração é uma tática comumente utilizada para fins de pesquisa amplos. De acordo com @Barbier2011, uma definição de mineração de dados é a identificação de padrões novos e acionáveis nos dados, de forma a extrair novos conhecimentos de conjuntos de dados. Algorítmos supervisionados e não-supervisionados são utilizados para identificar padrões nos dados. Para algorítmos supervisionados, a *classificação* é um método em que um algorítmo é treinado com um conjunto exemplo de dados com rótulos para cada elemento, de forma a aprender a rotular dados semelhantes. Similarmente, *clustering* é um método de agrupamento para mineração não-supervisionada, que identificam semelhanças entre elementos em dados para determinar suas distâncias. Estes métodos de agrupamentos são semelhantes à *detecção de comunidade*, pela qual são extraídas conexões implícitas de uma rede [@Aggarwal2011]. 

@Gandomi2015 explicam a análise de influência social como outra técnica na análise de redes sociais, que agrupa métodos de modelação e avaliação da influência de usuários e conexões em uma rede social. Métodos de análise de influência social são amplamente úteis em esforços de *brand awareness* e adoção de marca, auxiliando no marketing de influência. Adicionalmente, os autores descrevem o método de *previsão de conexões* como a análise de dados passados para tentar prever interações futuras, de forma a levar em consideração a natureza dinâmica e imprevisível das dinâmicas de redes sociais.

:::callout-note
NÃO VAMOS USAR ANÁLISE DE SENTIMENTO
<!-- 
A análise de sentimentos (também conhecida como mineração de opiniões) é o processo de analisar computacionalmente e identificar opiniões e julgamentos de um texto linguístico, podendo ser implementada em propósitos diferentes como *baseada em aspectos*, *a nível de documento* e *a nível de frase* [@Chakraborty2023]. A análise de sentimentos *baseada em aspectos* é capaz de classificar textos em aspectos diferentes e determinar sentimentos correspondentes por associação. O módulo *a nível de documento* analisa um documento inteiro, enquanto aquele *a nível de frase* limita-se a sentenças curtas como as de postagens em microblogues, que tendem a ter baixos limites de caracteres. 
@Bian2016 apontam que existem duas abordagens gerais para a análise de sentimentos: a primeira se baseia em um léxico como o Harvard General Inquirer, SentiWordNet ou Linguistic Inquiry, que associam escolhas de palavras a opiniões e atitudes. Esta abordagem visa descobrir a estrutura temática por trás de grandes conjuntos de documentos não-estruturados, através da análise das palavras por um algorítmo estatístico. A segunda abordagem, baseada em classificações, é um método supervisionado que requer conjuntos rotulados para o treinamento de um algorítmo. 
--->

apresentar ciência de dados como campo interdisciplinar que estuda os dados 
    - definir ciência de dados como área interdisciplinar (estatística, computação, conhecimento de domínio)
    - objetivo: transformar dados em informação útil para apoiar decisões
- qual é a relação com marketing? uso de dados digitais para compreender comportamento do consumidor, segmentação, monitoramento de marcas etc.

- workflow de projetos pontuais em ciência de dados
    - entendimento do problema de negócios
    - coleta de dados: introduz raspagem em linhas gerais
    - preparação e limpeza dos dados: tratamento de dados não estruturados  (texto com gírias, emojis, abreviações)
    - análise exploratória: estatísticas descritivas, frequências, nuvens de palavras
    - modelagem e outras técnicas de análise: análise de sentimentos, análise de conectividade, classificação, clustering, modelagem de tópicos
    - comunicação dos resultados: visualizações e interpretação para não especialistas
- usar
    - [Brodie, 2023](https://arxiv.org/abs/2306.16177)
    - [Cao, 2020](https://arxiv.org/abs/2007.03606) 
    - [R4DS](https://r4ds.hadley.nz/) para workflow de data science
:::


# Problema de pesquisa

Em dezembro de 2019, Jack Donsey, então CEO do Twitter Inc., anunciou que a empresa estaria financiando uma equipe de profissionais independentes para o desenvolvimento de um novo protocolo aberto e descentralizado para redes sociais, com a intenção de eventualmente implementá-lo para o próprio Twitter. Em 2021, o projeto se tornou uma organização independente do Twitter, dando origem ao Bluesky Social PCB. Um ano depois, em 2022, Elon Musk adquiriu o Twitter (renomeado como X) e a rede cessou todas relações de serviço com o Bluesky, que seguiu com sua proposta de desenvolver e impulsionar a adoção em larga escala de tecnologias para conversas públicas, abertas e descentralizadas. [@Bluesky2023]

A rede teve um grande aumento de usuários em 30 de agosto de 2024, quando a *X Brasil Internet Ltda.* e outras empresas relacionadas à Elon Musk tiveram seus funcionamentos integralmente suspensos em todo o Brasil por determinação de Alexandre de Moraes, ministro do Supremo Tribunal Federal. O motivo da suspensão foi o desobedecimento de ordens judiciais brasileiras na não nomeação de um representante legal dentro do prazo estipulado pelo ministro na intimação (PET 12.404 DF) de 18 de setembro de 2024. [@G12024]

A suspensão do X no Brasil durou cerca de 40 dias, encerrando em 8 de outubro de 2024 após o cumprimento das ordens judiciais pela rede e uma multa de 28,6 milhões de reais. Durante este período, a migração de usuários brasileiros para alternativas como o Bluesky foi impulsionada significativamente. Em 31 agosto de 2024, o Bluesky anunciou que havia batido mais de 1 milhão de novos usuários nos últimos 3 dias e que brasileiros estavam estabelecendo novos recordes de atividade na plataforma. [@G12024]

::: callout
O conceito de *sociedade plataformizada*, proposto por @Dijck2019, explica o fenômeno em que as lógicas das plataformas (como AirBnb, Google, Uber e outras) moldam a interação social, a economia e o exercicio da cidadania. Os autores dividem o ecossistema de plataformas entre plataformas infraestruturais e setoriais, em que as plataformas infraestruturais são as mais influentes e formam o coração do ecossistema sobre as quais outros aplicativos e plataformas setoriais podem ser construídos, sendo elas mecanismos de busca, navegadores, *e-mail*, plataformas de mensagem, redes sociais, lojas de aplicativos, *GPS*, sistemas de pagamento e hospedagem de arquivos. O segundo tipo, as plataformas setoriais, são aquelas que servem um nicho específico como alimentação, transporte, notícias ou hospitalidade [@Dijck2019]. Sendo assim, podemos entender a migração de usuários do X (centralizado, baseado em anúncios e de protocolo proprietário) para o Bluesky (descentralizado, sem anúncios e de protocolo aberto) como uma mudança de um ecossistema plataformizado fechado para um potencialmente mais aberto. Essa perspectiva é sustentada por @Plantin2018, que destaca como a utilização de interfaces de programação de aplicações (APIs) de plataformas infraestruturais por outros atores predominantes cria um ambiente virtual controlado por essas plataformas, que passam a "dominar um território" da internet anteriormente livre, centralizando-a para fins comerciais. O projeto que viria a se tornar o Bluesky surge em resposta a essa crescente centralização, buscando desenvolver um novo padrão descentralizado para conversas públicas em redes sociais -- o Protocolo AT (*Authenticated Transfer Protocol*).
:::

Em seu artigo sobre as consequências da algoritmização na sociedade, @Velkova2021 abordam a ideia de "políticas de reparo" midiáticas como sendo trabalhos corretivos em conjunto com e dentro de sistemas algorítmicos para fazê-los gerarem resultados não intencionais, em resposta a tendenciosidades ou "falhas" percebidas nos resultados de algorítmos. Similarmente, a migração em massa de usuários brasileiros do X para o Bluesky pode ser vista como uma forma de "reparo" ou "resistência algorítmica" diante da falha (interdição no Brasil) de uma plataforma centralizada, tornando necessário o reparo de seus tecidos sociais e comunicativos em um novo espaço onde possam reconstruir comunidades.

Ao mesmo tempo em que o X foi suspenso ocorria a 13ª edição do Campeonato Brasileiro de League of Legends (CBLOL), um torneio competitivo de *e-sports* de League of Legends no Brasil organizado anualmente pela Riot Games. Em 2024, o evento teve sua primeira etapa entre 20 de janeiro e 20 de abril e sua segunda etapa entre 1 de junho e 7 de setembro. Com partidas gerando um grande número de engajamento nas redes sociais, a produção de conteúdo por espectadores durante a segunda etapa do CBLOL 2024 foi diretamente impactada pela suspensão da rede social no Brasil, que teve seu início próximo às finais do campeonato e término somente depois que ele havia encerrado. [@CBLOL2024]

Diante disso, levanta-se a seguinte questão central:

> De que maneira o bloqueio do X no Brasil influenciou as dinâmicas de engajamento e produção de conteúdo sobre *e-sports* de League of Legends na rede social Bluesky?



# Objetivos

## Objetivo Geral

- Caracterizar como a suspensão das atividades do X no Brasil influenciou as dinâmicas de engajamento e produção de conteúdo sobre *e-sports* de League of Legends na rede social Bluesky.

## Objetivos Específicos

- Mensurar a flutuação no volume de postagens no Bluesky sobre League of Legends antes, durante e após a suspensão do X no Brasil.
- Caracterizar as dinâmicas de seguidores e influência social de usuários dentro de comunidades associadas à League of Legends.

# Justificativa

No meio digital, esforços de pesquisa acadêmica devem considerar que os objetos de estudo são em grande parte instáveis, seja pela efemeridade de *websites* (que podem ser alterados, redirecionados ou retirados do ar subitamente), atualizações de *software* ou modificações em serviços digitais que reconfiguram de alguma forma aquilo sendo estudado [@Rogers2009]. Tal característica se torna evidente com o rebranding do Twitter para X e a reconfiguração subsequente da plataforma após a aquisição de Elon Musk, que encerrou o acesso gratuito à API e passou a cobrar um serviço de inscrição em Fevereiro de 2023 [@EconomicTimes2025]. Como consequência, a mineração ou raspagem de postagens para estudos de percepção pública, análise de sentimentos, predição de consumo [@Bhattacharjee2017; @Chakraborty2023; @Bian2016] e outras metodologias de pesquisa semelhantes que utilizassem de dados do antigo Twitter se tornaram repentinamente irreplicáveis.

Em função desta constante mudança, @Rogers2009 argumenta que através do emprego de métodos virtuais, pesquisas relacionadas à internet devem deixar de focar na mensuração de quanto cultura virtual reflete a realidade para, em vez disso, diagnosticar as mudanças culturais e societais *através* da internet, como fonte de dados e não objeto de estudo. A suspensão do X no Brasil e a subsequente migração de usuários para o BlueSky, portanto, é um fenômeno digital que reflete uma mudança cultural e social e que pode vir a ser estudada através de métodos digitais.

Como @Jenkins2015 descrevem, os contextos tecnológicos, econômicos e legais afetam a forma em que a participação cultural se manifesta, com o ambiente atual de mídia sendo cada vez mais propício à propagação de conteúdo pela facilidade de apropriação, remixagem, recirculação e incorporação na natureza das tecnologias. Através dos esforços laborais de usuários na criação de conteúdo e promoção, estas plataformas comercializadas se tornam mais atrativas para novos usuários que agem simultaneamente como consumidores e produtores [@Terranova2000]. Essas mídias propagáveis, portanto, são representativas de valores sociais ou culturais dos usuários envolvidos, como @Jenkins2015 explicam:

>[...] se um público vai tomar para si a propagação do conteúdo de mídia ou a discussão sobre aquele conteúdo, é porque esse conteúdo atende a algum
propósito comunicativo para o público e porque se encaixa em suas conversas que estão em andamento (op.cit. p. 467-468).

Um dos maiores contribuidores em volume de *user generated content* nas redes sociais é a comunidade *gamer*, cuja cultura de assistir outros jogarem, presente desde os fliperamas e consoles domésticos até as batalhas *on-line*, consolidou-se como parte essencial da experiência dos jogos [@Taylor2019]. Dentre os jogos eletrônicos mais relevantes atualmente, League of Legends se destaca como um *e-sports* dos mais assistidos [@Cauteruccio2023], nos quais fãs possuem investimentos afetivos nos jogadores e são capazes de compartilhar experiências emocionais dentro do ecossistema de espectadores [@Cheung2011]. Neste ambiente, os jogadores profissionais e *streamers* comentadores de *e-sports*, de atuação análoga aos influenciadores digitais, geram uma conexão mais próxima entre os espectadores e os jogos que transmitem [@Glucksman2017]. 

A união desses diversos fatores, pareados com a prominência dos jogos eletrônicos e dos *e-sports* na sociedade brasileira [@PGB2025; @PGB2024], fazem da discussão acerca de *e-sports* de League of Legends nas redes sociais um tópico com grande volume de dados digitais empíricos valiosos para a criação de conhecimento social. Portanto, a suspensão do X no Brasil, por coincidir com o CBLOL, torna possível examinar como as dinâmicas de engajamento e produção de conteúdo dessa comunidade no BlueSky foram afetadas pela migração através da análise de redes sociais, de forma a gerar uma melhor compreensão do impacto desse acontecimento digital.

<!--
Unir BlueSky, redes sociais, queda do X e LoL e apontar a significância
--->

# Metodologia

[A Extração de Informações consiste na extração automática de informações estruturadas como entidades, relações entre entidades e atributos descrevendo entidades de fontes desordenadas, que permite buscas mais aprofundadas do que as possíveis por buscas de palavras-chave]{.mark} [@Sarawagi2008]. [Para a Extração de Informações disponíveis *on-line*]{.mark}, esses dados podem ser acessados através de uma interface de programação de aplicações (API) própria do *site* (plataformas) em que são hospedados, porém grandes fontes como Facebook, Google e X têm recentemente limitado ou restringido o acesso gratuito às suas APIs em virtude do valor comercial dessas informações, dificultando a obtenção de dados reais para fins acadêmicos [@Batrinca2014]. Dentre as redes sociais mais relevantes atualmente, o Bluesky se destaca como uma das únicas que ainda permite acesso irrestrito e gratuito à sua API até o momento desta redação, desde que utilize-se de uma autenticação única atrelada a uma conta na plataforma.
 
[Dada a coleta de dados minerados, é possível empregar técnicas de análise de redes sociais para extrair *insights* acionáveis de um grande volume de informações desordenadas]{.mark}. Para a detecção de comunidades, @Aggarwal2011 sugere a representação através de grafos, uma estrutura matemática composta por um conjuntos nós ou vértices e um conjunto de arestas, em que os nós representam as entidades de interesse e as arestas representam as interações ou relações entre elas. Esses grupos de nós são então definidos como comunidades distintas se suas conexões internas são mais fortes do que com o resto da rede. Sendo assim, redes sociais podem ser modeladas em grafos $G = \{V, E\}$, onde $V$ é um conjunto de nós e $E$ um conjunto de arestas. [No contexto de redes sociais como o Bluesky, nós podem representar entidades como perfis de usuários, postagens e comentários, enquanto as arestas que os conectam podem representar interações como segue, é seguido, curtiu, respondeu à, repostou etc.]{.mark}

::: callout
A medida de influência social na análise de redes sociais, de acordo com @Aggarwal2011, parte do princípio que as pessoas tendem a seguir ou adotar os comportamentos de seus amigos ou vizinhos, fenômeno conhecido como homofilia. @Freeman1978, similarmente, aponta que alguém numa rede social em uma posição que permita contato direto com muitas outras pessoas pode vir a ser visto como um importante canal de informação e um ponto focal das comunicações. Essa influência pode ser entendida como um efeito direcional de um nó A para outro nó B, relacionado à força da aresta de A para B, ao mesmo tempo em que a semelhança nas "vizinhanças" (nós próximos) de A e B representam a força da aresta que os conecta, com muitos vizinhos em comum representando um laço forte e vice-versa [@Aggarwal2011]. 
:::

As medidas de centralidade podem ser agrupadas em duas categorias: medidas radiais e medidas mediais, em que as medidas radiais avaliam caminhadas aleatórias que começam ou terminam em um determinado nó e as medidas mediais avaliam caminhadas aleatórias que passam por um determinado nó [@Aggarwal2011]. [Dentre essas, as mais relevantes para o presente trabalho são as medidas de centralidade de grau, centralidade de proximidade e centralidade de intermediação.]{.mark}

:::callout
A medida de centralidade de grau é a medida de centralidade radial mais simples, contando o número de arestas que originam de um nó $i$ tal que $c_i^{DEG}=deg(i)$, em que $deg(i)$ representa o grau do nó e $c_i^{DEG}$ a centralidade de grau [@Aggarwal2011]. Pode-se especular, portanto, que nós com uma centralidade de grau relativamente alta tem uma visibilidade ampliada ou um alto potencial de atividade em comunicação dentro de uma rede social, enquanto nós com um baixo grau são vistos como periféricos e de pouco envolvimento nos processos comunicativos [@Freeman1978].

Outro grupo de medidas radiais são as de centralidade de proximidade. A medida mais popular nesse grupo é a centralidade de proximidade de Freeman ($c_i^{CLO}$), que mede a centralidade de um nó $i$ com base na média das distâncias mais curtas para todos os outros nós no grafo, definida por $c_i^{CLO}=e^T_iS\mathbf1$, na qual $S$ é a matriz que contém o caminho de menor distância entre os nós $i$ e $j$ e 1 é um vetor ou matriz de uns [@Aggarwal2011].

A centralidade de intermediação de Freeman ($c_i^{BET}$), medida de centralidade medial mais conhecida, mede o quanto um nó $i$ está presente nos caminhos mais curtos da rede e é dada por $c_i^{BET}=\sum_{j,k}\frac{b_{jik}}{b_{jk}}$, onde $b_{jk}$ é o número de caminhos mais curtos entre os nós $j$ e $k$ e $b_{jik}$ é o número de caminhos mais curtos entre $j$ e $k$ que passem pelo nó $i$ [@Aggarwal2011]. Essa medida se baseia na suposição de que uma pessoa que está estrategicamente posicionada entre duas comunidades possui um potencial de controle sob as comunicações destas e, portanto, ocupa uma posição central [@Freeman1978].
:::


:::callout-note
- técnicas utilizadas neste trabalho
  - análise de frequência e exploratória: contagem de palavras, bigramas, visualização
  - análise de conectividade: análise de índices de conexão, de centralidade
  - análise de sentimentos (???)
:::



## Tecnologias Utilizadas

:::callout
Inicialmente, realizou-se uma busca por artigos científicos indexados no Portal de Periódicos CAPES, com o auxílio do acesso CAFe (Comunidade Acadêmica Federada), que permite que universitários acadêmicos acessem toda a base. A natureza da primeira parte do trabalho é ser descritiva-exploratória, com abordagem quanti-qualitativa, a fim de entregar um embasamento teórico consiso.

Segundo princípios da Netnografia, defendida por @Hide2005, pesquisar utilizando a internet como objeto de estudo explicita o caráter multidisciplinar e multiparadigmático das ciências sociais, que, com a concepção do conceito de netnografia e comunidade online, "moldou uma geração de estudos".

A Análise de Redes Sociais (ARS) pode ser caracterizada como um método de netnografia online, com objetivo de analisar discursos mediados por computador e com potencial de moldar a compreensão a cerca do fenômeno da utilização da internet por pessoas [@Hide2005].


-Objetivo: descritiva e exploratória (dificilmente aplicada em marketing)
-Procedimentos técnicos:
-Estudo de caso da interação de usuários durante a queda do X no BR e Etnografia
-Persquisa transversal com um recorte no tempo e momento específico.
:::

### Ambiente Computacional Estatístico R

:::callout-note
Achar alguma bibliografia pertinente como espécie de introdução
:::

A linguagem R têm se consolidado como uma das principais ferramentas da ciência de dados contemporânea, oferecendo recursos avançados para manuseio de dados, análise estatística, modelagem e visualização de informações. De acordo com @Wickham2017, o R é "uma linguagem poderosa e flexível, projetada para análise estatística e visualização de dados, tornando-se uma das principais ferramentas da ciência de dados moderna”. No presente trabalho, o R é utilizado para realizar a mineração, tratamento e formatação de dados provenientes da rede social Bluesky.


### Mineração de Dados

Em seu artigo sobre abordagens quantitativas para a comparação de padrões comunicativos no Twitter (atual X), @Bruns2012 utiliza da API de busca através da plataforma *yourTwapperkeeper* para extrair um conjunto de dados de postagens (*tweets*) que contenham palavras-chave ou *hashtags* determinadas pelo operador. No Bluesky, um processo equivalente pode ser realizado através do pacote '{atrrr}' do R para acessar a API da rede e buscar postagens dentro de um critério estabelecido.

Para descrever os padrões comunicativos que podem ser observados dentro deste conjunto de interações, utiliza-se de um catálogo de métricas, divididas entre três grupos em razão 1:9:90 [@Bruns2012]:

- o 1% de usuários líderes em atividade;
- os 9% seguintes de usuários mais ativos;
- os 90% restantes de usuários.

Desses grupos, foram calculadas as métricas:

- o número de postagens no conjunto de dados;
- o número de usuários únicos que contribuem para o conjunto de dados;
- a porcentagem de postagens originais no conjunto de dados (ou seja, postagens que não são respostas nem *reposts*);
- a porcentagem de respostas genuínas no conjunto de dados (ou seja, respostas que não são *reposts*);
- a porcentagem de *reposts* no conjunto de dados;
- a porcentagem de postagens no conjunto de dados que contêm URLs.

Dessa forma, é possível medir dentro do conjunto de dados o quão dominantes na conversa geral são os usuários mais ativos e observar diferenças nos padrões de atividades dos três grupos [@Bruns2012]. O mesmo processo pode ser aplicado à critérios ou hashtags não relacionados ao tema de pesquisa para inseri-lo em um contexto mais amplo. Ademais, para analisar o impacto da suspensão do X nas dinâmicas de comunidade no Bluesky, pode-se dividir conjuntos de dados entre períodos temporais, realizando a mesma coleta de dados para:

:::callout
- as 5 semanas anteriores à suspensão (26/07/2024 - 30/09/2024);
- as 5 semanas em que o X esteve indisponível (31/09/2024 - 08/10/2024);
- as 5 semanas posterior ao retorno da rede (09/10/2024 - 13/11/2024).
:::

:::callout-note
Como citar essas fontes no texto abaixo?
Biblioteca ATRR
https://cran.r-project.org/web/packages/atrrr/atrrr.pdf


Protocolo AT  by Bluesky 
https://docs.bsky.app/docs/api/app-bsky-feed-get-post-thread
Repositório: https://github.com/bluesky-social


Para a realização desta pesquisa netnográfica, utilizou-se da documentação oficial do Protocolo AT do Bluesky como base para o processo de mineração dos dados. Essa etapa teve caráter exploratório, visando compreender o funcionamento estrutural da rede social e orientar a construção do código de mineração de dados a partir da API.

Durante a fase exploratória, identificou-se a biblioteca para o R chamada `{atrrr}`. Essa biblioteca implemeta o protocolo AT e permite realizar chamadas à API da plataforma, facilitando assim, o processo de extração dos dados necessários para o desenvolvimento da pesquisa.
:::

:::callout-note
Comentando a seção abaixo enquanto averiguamos se vamos manter o bskyr ou mudar totalmente para o atrrr

<!-- 
#### Pacote `{bskyr}` do RStudio

Tendo sua versão 0.3.0 disponibilizada em 22 de julho de 2025, o `{bskyr}` é um pacote do R Studio que providencia uma interface com a Bluesky Social API via HTTP (*HyperText Transfer Protocol*), permitindo extrações de dados da rede [@bskyr]. APIs como a API Bluesky Social permitem que um *software* cliente enviem uma solicitação a um *software* servidor e receba dele uma resposta.

As APIs de HTTP são ferramentas que permitem a comunicação entre diferentes sistemas, funcionando como pontes entre cliente e servidor. No caso do Bluesky, essa comunicação utiliza um conjunto de protocolos chamado XRPC (*eXtensible Remote Procedure Call*), que define como essas trocas devem acontecer, no qual cada função da API possui um endpoint — ou seja, um endereço específico na web — identificado por um código chamado NSID (*NameSpace IDentifier*) responsável por organizar e padronizar essas interações. As mensagens trocadas seguem formatos estruturados, geralmente em JSON (*JavaScript Object Notation*), o que garante que ambos os lados da comunicação “falem a mesma língua”. Esse tipo de arquitetura é comum em redes abertas e descentralizadas, como o próprio Bluesky, favorecendo a interoperabilidade e a consistência na troca de dados [@bskyr].

O conteúdo da biblioteca está em sua documentação [@bskyr]. A seguir, algumas das funções que pretendemos utilizar:

- `bs_auth()`: autentica um usuário
- `bs_search_posts()`: encontra posts específicos dentro de um critério de pesquisa
- outros


Os dois tipos de requisições que podem ser expressos em Léxicos são "consulta" (HTTP GET) e "procedimento" (HTTP POST). Seguindo a semântica HTTP REST, as consultas (GET) podem ser armazenadas em cache e não devem alterar o estado do recurso. Os procedimentos não podem ser armazenados em cache e podem alterar o estado.[Protocolo usado no API HTTP (XRPC)](https://atproto.com/pt/specs/xrpc) 

Lista de NSID importantes:


#### App Paswords

No processo de raspagem de dados, foi solicitado o *App Pasword*, uma prática mais segura para reduzir riscos quando *logamos* como clientes em partes terceiras e em aplicações web. São usadas como a chave de acesso assim como a senha, mas concede permissões restritas, impedindo ações destrutivas. [Protocolo usado no API HTTP (XRPC)](https://atproto.com/pt/specs/xrpc)

- Achar alguma bibliografia pertinente como espécie de introdução
- Mencionar bibliotecas do R 

-->
:::

### Análise de Dados em Rede

A partir das métricas estabelecidas durante a mineração de dados, @Bruns2012 realiza as seguintes análises, que servem como embasamento para a análise de padrões comunicativos:

- contribuições relativas dos três grupos de usuários;
- longetividade do termo em comparação à porcentagem de posts contribuídos pelo grupo de 90% dos usuários;
- porcentagens relativas dos diferentes tipos de postagens;
- porcentagem de URLs em posts vs. porcentagem de *reposts*;
- porcentagem de postagens contribuídas por usuários líderes em atividade vs. porcentagem de URLs em postagens.

::: callout
No presente trabalho, utilizou-se como métrica principal de propagação de opiniões as curtidas (*likes*) em postagens (*skeets*) com o termo CBLOL. Essa escolha é baseada na premissa que curtidas representam um engajamento ativo e singular e que demonstram concordância ou aprovação em relação a um conteúdo pontual, enquanto a métrica de seguidores é indicativa somente de alcance potencial sem garantir engajamento ou influência real. @Moon2022 demonstram que o número de seguidores não é sempre proporcional ao engajamento para campanhas de marketing de influência, com uma uma curva de formato U inverso sendo mais representativa da relação entre número de seguidores e engajamento, onde o engajamento é mais alto para influenciadores com um número moderado de seguidores. Além disso, estudos relevam que usuários de redes sociais tendem a engajar mais (em termos de curtidas e *reposts*) conteúdos de contas que seguem menos pessoas, por as interpretarem como mais autônomas [@Valsesia2020]. Em contraste, curtidas representam uma forma ativa de engajamento com peso menor que os comentários por necessitarem de menos esforço [Moon2022], cujos números ainda tendem a ser significantemente menores do que o total de seguidores, demonstrando a passividade destes em muitos casos [@Avelino2020]. A união destes fatores, portanto, evidencia as curtidas como sendo a métrica mais apropriada para medir a resposta efetiva do público e a dinâmica real de disseminação do conteúdo em redes sociais.
:::


:::callout-note
- Achar alguma bibliografia pertinente como espécie de introdução
- Mencionar bibliotecas do R
:::

## Fonte dos Dados

:::callout-note
O Bluesky é uma rede social de API aberta construída a partir do Protocolo AT, uma fundação descentralizada para redes sociais públicas. Lançada ao público oficialmente em 2024, uma das propostas da rede social que justificam a escolha da mesma para objeto deste estudo é o acesso aberto à sua arquitetura. A abertura do sistema proporciona a interação de seus conjuntos de dados para a moderação de conteúdos de mídia social e gerenciamento de comunidades (tanto partindo de usuários como partindo de pesquisadores). [@Kleppmann2024]


- Mencionar BlueSky
- Caracterizar período
- Fundamentar porquê do período
:::

# Resultados

# Discussão

# Conclusão

## Principais achados

## Limitações

## Trabalhos futuros

# Referências

\appendix

# Apêndices

## Apêndice A -- script de raspagem ????

# Anexos

## Anexo A -- Material complementar ????

